[versions]
kotlin = "2.0.0"
spotless = "6.25.0"
junit = "5.11.3"
assertj = "3.26.3"

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]

junitBom = { module = "org.junit:junit-bom", version.ref = "junit" }
junitJupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junitJupiterApi = { module = "org.junit.jupiter:junit-jupiter-api" }
junitJupiterParams = { module = "org.junit.jupiter:junit-jupiter-params" }
assertjCore = { module = "org.assertj:assertj-core", version.ref = "assertj" }

[bundles]
test = ["junitJupiterEngine", "junitJupiterApi", "junitJupiterParams", "assertjCore"]
